# Catppuccin Latte for Foot
# https://github.com/catppuccin/foot

[colors-dark]
alpha=1.0
background=eff1f5
foreground=4c4f69

## Normal/regular colors (color palette 0-7)
regular0=bcc0cc  # black (Surface 1)
regular1=d20f39  # red
regular2=40a02b  # green
regular3=df8e1d  # yellow
regular4=1e66f5  # blue
regular5=ea76cb  # magenta
regular6=179287  # cyan
regular7=5c5f77  # white (Subtext 1)

## Bright colors (color palette 8-15)
bright0=acb0be   # bright black (Surface 2)
bright1=d20f39   # bright red
bright2=40a02b   # bright green
bright3=df8e1d   # bright yellow
bright4=1e66f5   # bright blue
bright5=ea76cb   # bright magenta
bright6=179287   # bright cyan
bright7=6c6f85   # bright white (Subtext 0)

## Selection colors
selection-foreground=eff1f5
selection-background=dc8a78

## Cursor colors
cursor=eff1f5 dc8a78

## URL color
urls=dc8a78
