#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = quickshell & hyprpaper

exec-once = [workspace 1 silent] zen-browser

# Workspace 2 - Grouped apps
exec-once = [workspace 2 silent] Telegram
exec-once = [workspace 2 silent] legcord
# exec-once = [workspace 2 silent] zen-browser
exec-once = [workspace 2 silent] thunderbird

exec-once = [workspace 3 silent] foot -e tmux

exec-once = hyprctl dispatch workspace 3
