scrolling {
    column_width = 0.5
    direction = right
    explicit_column_widths = 0.5, 0.6, 1.0
}

# Resize windows like in Niri
# Cycles through 0.5, 0.6 and 1.0 sizes
bind = $mainMod, R, layoutmsg, colresize +conf
