#!/bin/bash

# deps for wayland
# grim slurp wl-clipboard 

capture_wayland() {
    local path=~/Images/screenshot.png

    if [ "$1" = "root" ]; then
        grim -t png "$path"
    elif [ "$1" = "area" ]; then
        if ! command -v slurp >/dev/null; then
            echo "Error: slurp is required for area selection in Wayland"
            return 1
        fi
        grim -t png -g "$(slurp | awk '{
            split($1, a, ",");
            split($2, b, "x");
            printf "%d,%d %dx%d", a[1]+1, a[2]+1, b[1]-2, b[2]-2
        }')" "$path"
    fi
    wl-copy < "$path"
}

capture_x11() {
    if [ "$1" = "root" ]; then
        xwd -root -out ~/Images/screenshot.xwd
    elif [ "$1" = "area" ]; then
        import ~/Images/screenshot.xwd
    fi
    convert ~/Images/screenshot.xwd ~/Images/screenshot.jpg
    rm ~/Images/screenshot.xwd
    xclip -sel clipboard -t image/jpg < ~/Images/screenshot.jpg
}

if [ "$XDG_SESSION_TYPE" = "wayland" ] || [ -n "$WAYLAND_DISPLAY" ]; then
    capture_wayland "$1"
else
    capture_x11 "$1"
fi
