general.import = [ "~/.cache/wal/colors-alacritty.toml" ]

[window]
opacity = 0.9

[font]
size = 16.1

[font.bold]
family = "MonaspiceKr Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceKr Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspiceKr Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceKr Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

